# A reusable job to build images supplied a version

name: Generic build action

on: workflow_dispatch


jobs:
  build-images:
    name: Build container images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@master
        id: buildx
        with:
          install: true

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}


      - name: Build and push backend
        uses: docker/build-push-action@v3
        with:
          context: .
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ghcr.io/zaviermiller/railsimage:latest
          target: production
          cache-from: type=registry,ref=ghcr.io/zaviermiller/railsimage:cache
          cache-to: type=registry,ref=ghcr.io/zaviermiller/railsimage:cache,mode=max

        # This ugly bit is necessary if you don't want your cache to grow forever
        # until it hits GitHub's limit of 5GB.
        # Temp fix
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896

